# MKV Slimmer configuration

# Languages to keep (ordered by preference - first available becomes default)
audio:
  keep_languages:
    - jpn    # Japanese (first preference)
    - und    # Undefined (fallback)
  
subtitles:
  keep_languages:
    - hun    # Hungarian (first preference)
    - und    # Undefined (second preference)
    - eng    # English (third preference)
    - jpn    # Japanese (fourth preference)

# Processing options
processing:
  dry_run: false
