# MKV Slimmer configuration

# Languages to keep (ordered by preference - first available becomes default)
audio:
  keep_languages:
    - jpn    # Japanese (first preference)
    - und    # Undefined (fallback)
  
subtitles:
  # Subtitle preferences can be:
  # - Language only: "eng"
  # - Language with title prefix: "eng, Dialogue"
  # The first matching subtitle becomes default
  keep_languages:
    - hun    # Hungarian (first preference)
    - und    # Undefined (second preference)
    - "eng, Dialogue"  # English with title starting with "Dialogue"
    - eng    # English (any title)
    - jpn    # Japanese (fourth preference)

# Processing options
processing:
  dry_run: false
