# MKV Slimmer configuration

# Languages to keep (ordered by preference - first available becomes default)
audio:
  keep_languages:
    - jpn    # Japanese (first preference)
    - und    # Undefined (fallback)
  
subtitles:
  keep_languages:
    - hun    # Hungarian (first preference)
    - und    # Undefined (second preference)
    - eng    # English (third preference)
    - jpn    # Japanese (fourth preference)
  forced_only: false     # Keep all matching languages, not just forced

# Note: Video and attachment streams are always kept

# Output preferences  
output:
  suffix: "_slimmed"
  overwrite: false

# Processing options
processing:
  dry_run: false